### PR TITLE
BinarySearch Java and Kotlin

### PR DESCRIPTION
**Pull request by shobhitbehl98**

### CODE REVIEW

**Comment by Sunchit** [comment]
@shobhitbehl98 great seeing your PR after long ✌🏼

**Comment by shobhitbehl98** [comment]
Well Moksha was going on so couldn't PR on those days

**Comment by shobhitbehl98** [comment]
> @shobhitbehl98 great seeing your PR after long ✌🏼

Moksha was going on for last couple days so couldn't PR, now i'll be more regular

**Comment by Sunchit** [comment]
no worries, now I could connect the dots.. I hope you throughly enjoyed at it especially KK concert. Also, this year it was much waited after 2 years of lockdown

**Pull request merged**
