### PR TITLE
JAN 2022

### PR DESCRIPTION
**Pull request by shyam2520**
### JAN 2,3,4

- C++ code added 
- Readme.md  updated

### CODE REVIEW

**Comment by shyam2520** [comment]
Shoudl I create a PR once in 3 days or everyday ? @Sunchit

**Review by Sunchit — APPROVED** [review]
💪🏽

**Comment by Sunchit** [comment]
@shyam2520 , whatever you are comfortable with. You do daily challenge everyday then it is better to raise the PR on daily basis. However, whatever is comfortable to you.

**Comment by shyam2520** [comment]
Ok got it thanks

**Pull request merged**
