### PR TITLE
fixing original solution and a trie based solution for new testcases 

### PR DESCRIPTION
**Pull request by saiyashwanth**
#### Few key points to remember before you raise a pull request for your solution

- Please add link to the problem before the solution.
- Don't forget to update readme. It will help a lot of developers navigate to your solution.
- Add your solution in correct folder categorized by langauge in which you code.
  - Create separate folder for python, c++, or any other language if it does not exist.
- Most important don't forget to your name as "@author <Name>" at the top of your solution.

### CODE REVIEW

**Comment by saiyashwanth** [comment]
https://leetcode.com/problems/palindrome-pairs/

**Comment by saiyashwanth** [comment]
in the solution given by sunchit the only modification I did was to precompute the reverse of all words and use it when needed.

**Comment by saiyashwanth** [comment]
also have given alternative approach using trie, check that out too.

**Comment by Sunchit** [comment]
Super helpful

**Pull request merged**
